table '@ @ MEDIDAS'
	lineageTag: 7982f041-0fea-4403-8cd1-ba844da79562

	measure 'C2 - Cartao - %PopulacaoBeneficida' = DIVIDE([C2 - Cartao - PopulacaoBeneficiada],sum('@ @ MUNICÍPIOS BRASIL'[POPULAÇÃO]),0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 6b820224-9cc3-4d57-a98a-cfb6d7f80def

	measure 'C2 - Cartao - PopulacaoBeneficiada' = if(CALCULATE(SUM('@ @ MUNICÍPIOS BRASIL'[POPULAÇÃO]),FILTER('@ @ MUNICÍPIOS BRASIL','@ @ MUNICÍPIOS BRASIL'[MUNICIPIO] in ALLSELECTED('C2 - STATUS'[MUNICÍPIO])))=0,0,CALCULATE(SUM('@ @ MUNICÍPIOS BRASIL'[POPULAÇÃO]),FILTER('@ @ MUNICÍPIOS BRASIL','@ @ MUNICÍPIOS BRASIL'[MUNICIPIO] in ALLSELECTED('C2 - STATUS'[MUNICÍPIO]))))
		formatString: #,0
		lineageTag: c8fdc031-55e5-4079-bc0a-dabbb1bf6a54

	measure 'C2 - Cartao - PopulacaoTotal' = IF(SUM('@ @ MUNICÍPIOS BRASIL'[POPULAÇÃO])=0,0,SUM('@ @ MUNICÍPIOS BRASIL'[POPULAÇÃO]))
		formatString: #,0
		lineageTag: 38fdb752-5425-4235-a064-f6c73e0d38aa

	measure 'C3 - Cartao - %PopulacaoBeneficida' = DIVIDE([C3 - Cartao - PopulacaoBeneficiada],[C3 - Cartao - PopulacaoTotal],0)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 7f4ace2d-7146-4ee8-ab3a-f524f51b6386

	measure 'C3 - Cartao - PopulacaoBeneficiada' = if(CALCULATE(SUM('@ @ MUNICÍPIOS BRASIL'[POPULAÇÃO]),FILTER('@ @ MUNICÍPIOS BRASIL','@ @ MUNICÍPIOS BRASIL'[MUNICIPIO] IN SELECTCOLUMNS(CALCULATETABLE('C3 - STATUS','C3 - STATUS'[STATUS DO TRECHO]<>"AGUARDANDO O.S."),"MUN",[MUNICÍPIO])))=0,0,CALCULATE(SUM('@ @ MUNICÍPIOS BRASIL'[POPULAÇÃO]),FILTER('@ @ MUNICÍPIOS BRASIL','@ @ MUNICÍPIOS BRASIL'[MUNICIPIO] IN SELECTCOLUMNS(CALCULATETABLE('C3 - STATUS','C3 - STATUS'[STATUS DO TRECHO]<>"AGUARDANDO O.S."),"MUN",[MUNICÍPIO]))))
		formatString: #,0
		lineageTag: d9859488-e98b-4ce3-a154-5b6f8985ce6b

	measure 'C3 - Cartao - PopulacaoTotal' = IF(SUM('@ @ MUNICÍPIOS BRASIL'[POPULAÇÃO])=0,0,SUM('@ @ MUNICÍPIOS BRASIL'[POPULAÇÃO]))
		formatString: #,0
		lineageTag: 51e7841e-a882-4f72-980c-abd7e74e9e17

	measure 'C2 - Cartao - CursosDAgua' = if(DISTINCTCOUNT('C2 - STATUS'[CURSO D´ÁGUA])=0,0,DISTINCTCOUNT('C2 - STATUS'[CURSO D´ÁGUA]))
		formatString: 0
		lineageTag: 0521387d-0673-4635-afe7-2344835b3ea0

	measure 'C2 - Cartao - Extensao' = IF(sum('C2 - STATUS'[EXTENSÃO])=0,"-",Sum('C2 - STATUS'[EXTENSÃO]))
		lineageTag: 15fb82b2-4687-4af5-8a4c-80989c0dfdf0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'C2 - Cartao - Municipios' = IF(distinctcount('C2 - STATUS'[MUNICÍPIO])=0,0,distinctcount('C2 - STATUS'[MUNICÍPIO]))
		formatString: 0
		lineageTag: 6f63d4c7-3898-46e6-9f51-e6175d231c3d

	measure 'C2 - Cartao - ValorLiquidado' = if(Sum('C2 - MEDIÇÃO COM VOLUME'[VALOR MEDIDO])=0,0,sum('C2 - MEDIÇÃO COM VOLUME'[VALOR MEDIDO]))
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 54bcd890-6507-4451-b91e-928ab35279d8

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'C2 - Cartao - VolumeMedicao' = IF(SUM('C2 - MEDIÇÃO COM VOLUME'[VOLUME MEDIDO])=0,0,SUM('C2 - MEDIÇÃO COM VOLUME'[VOLUME MEDIDO]))
		lineageTag: e67f585c-ad67-400d-9e04-a49078486344

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'C2 - Cartao - QuantidadeContrato' = if(distinctcount('C2 - CONTRATO CONTROLE'[CODIGO DE BUSCA])=0,0,distinctcount('C2 - CONTRATO CONTROLE'[CODIGO DE BUSCA]))
		formatString: 0
		lineageTag: 1802cd80-1b91-4ea0-99d4-28582d3bf976

	measure 'C2 - Cartao - TotalContratual' = if(sum('C2 - CONTRATO CONTROLE'[VALOR TOTAL-CONTRATO])=0,0,sum('C2 - CONTRATO CONTROLE'[VALOR TOTAL-CONTRATO]))
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 602e3b99-39ef-48c1-b70d-f265e7da09a7

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'C2 - Cartao - ValorPrevisto' = IF(SUM('C2 - ATA'[VALOR-ATA])=0,0,SUM('C2 - ATA'[VALOR-ATA]))
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 719c2fc2-1f8c-4567-9926-a9ca025a7788

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'C3 - Cartao - CursosDAgua' = if(DISTINCTCOUNT('C3 - STATUS'[CURSO D´ÁGUA])=0,0,DISTINCTCOUNT('C3 - STATUS'[CURSO D´ÁGUA]))
		formatString: 0
		lineageTag: 75dd045f-269c-4088-a51e-f31ac11f7409

	measure 'C3 - Cartao - Extensao' = IF(sum('C3 - STATUS'[* EXTENSÃO (m)])=0,"-",Sum('C3 - STATUS'[* EXTENSÃO (m)]))
		formatString: #,0
		lineageTag: fd9d0f41-71d9-49b6-8019-a6b8d22c04ef

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'C3 - Cartao - Municipios' = IF(distinctcount('C3 - STATUS'[MUNICÍPIO])=0,0,distinctcount('C3 - STATUS'[MUNICÍPIO]))
		formatString: 0
		lineageTag: 55aadae9-395f-4e3c-9e84-fa3b53f55b44

	measure 'C3 - Cartao - ValorLiquidado' = if(Sum('C3 - MEDIÇÕES'[VALOR])=0,0,sum('C3 - MEDIÇÕES'[VALOR]))
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: f0fbd9bb-5c2b-4e1a-89fc-21578804dcdf

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'C3 - Cartao - VolumeMedicao' = IF(SUM('C3 - MEDIÇÕES'[VOLUME MEDIDO])=0,0,SUM('C3 - MEDIÇÕES'[VOLUME MEDIDO]))
		lineageTag: 67f7d0b7-0368-4d21-a20f-5f30cc6da696

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'C3 - Cartao - QuantidadeContrato' = if(distinctcount('C3 - CONTRATO CONTROLE'[CONTRATO])=0,0,distinctcount('C3 - CONTRATO CONTROLE'[CONTRATO]))
		formatString: 0
		lineageTag: 14b92d2b-16ca-45e7-9b2f-7fc1a0579f01

	measure 'C3 - Cartao - ValorEmpenhado' = IF(CALCULATE(sum('C3 - CONTRATO CONTROLE'[VALOR CONTRATUAL COM ADITIVO]),FILTER('C3 - CONTRATO CONTROLE','C3 - CONTRATO CONTROLE'[STATUS DO CONTRATO]<>"EM ELABORAÇÃO"))=0,0,CALCULATE(sum('C3 - CONTRATO CONTROLE'[VALOR CONTRATUAL COM ADITIVO]),FILTER('C3 - CONTRATO CONTROLE','C3 - CONTRATO CONTROLE'[STATUS DO CONTRATO]<>"EM ELABORAÇÃO")))
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: c06e36ba-2ddd-41f8-bb90-35cc842db613

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'C3 - Cartao - ValorPrevisto' = IF(SUM('C3 - ATA'[VALOR])=0,0,SUM('C3 - ATA'[VALOR]))
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: fe9ddf55-7937-43ff-bd06-395a28def522

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'C1 - Cartao - Municipios' = if(distinctCOUNT('C1 - INVESTIMENTO'[MUNICÍPIOS]) = 0,0,distinctcount('C1 - INVESTIMENTO'[MUNICÍPIOS]))
		formatString: 0
		lineageTag: 6bcaad2c-3297-4454-854b-90170c859bd8

	measure 'C1 - Cartao - InvestimentoTotal' = if(sum('C1 - INVESTIMENTO'[INVESTIMENTO TOTAL]) = 0, 0, sum('C1 - INVESTIMENTO'[INVESTIMENTO TOTAL]))
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: fdc4f6e7-217a-4c74-a04a-1c0cdb81d6b9

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'C1 - Cartao - VolumeTotal' = if(sum('C1 - INVESTIMENTO'[VOLUME TOTAL])=0,0,Sum('C1 - INVESTIMENTO'[VOLUME TOTAL]))
		lineageTag: e6e0118d-a2a0-403e-a3b7-e001efbf6384

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'C3 - Cartao - SaldoPrevisto' = [C3 - Cartao - ValorPrevisto] - [C3 - Cartao - ValorEmpenhado]
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 0fdc34cd-33e9-48fe-8a13-2cfab2def66a

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'C3 - Cartao - ValorComprometido' = IF(SUM('C3 - OS CONTROLE'[VALOR ESTIMADO])=0,0,SUM('C3 - OS CONTROLE'[VALOR ESTIMADO]))
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: b949f5a1-c1ae-4573-8a77-30b7fb2c62fd

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'C3 - Tabela - %Contrato/ATA' = Round(divide(sum('C3 -  CONTRATOS'[VALOR]),SUM('C3 - ATA'[VALOR])),4)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 23ba2f3a-df88-4fdd-94ed-6b12e8e52b71

	measure 'C3 - Tabela - QuantidadeATA-Contrato' = round(SUM('C3 - ATA'[QUANTIDADE])-SUM('C3 -  CONTRATOS'[QUANTIDADE]),4)
		formatString: #,0.00
		lineageTag: 1c25e8e2-cf0a-434e-9412-d446c917aeed

	measure 'C3 - Tabela - ValorATA-Contrato' = ROUND(SUM('C3 - ATA'[VALOR])-SUM('C3 -  CONTRATOS'[VALOR]),4)
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: bea0b8ff-a299-4553-9498-1d6422ff8e89

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'C3 - Tabela - %OS/Contrato' = round(DIVIDE(SUM('C3 - OS'[VALOR]),SUM('C3 -  CONTRATOS'[VALOR])),4)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 079fe696-03e8-4ba2-8f32-29fc10683e23

	measure 'C3 - Tabela - QuantidadeContrato-OS' = round(sum('C3 -  CONTRATOS'[QUANTIDADE])-sum('C3 - OS'[QUANTIDADE]),2)
		lineageTag: 8166b713-77ca-465e-b8a0-716a4e16bfef

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'C3 - Tabela - ValorContrato-OS' = round(sum('C3 -  CONTRATOS'[VALOR])-sum('C3 - OS'[VALOR CALCULADO]),2)
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 01eff1c6-20fa-4eef-a12a-bff17cddaefc

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'C3 - Tabela - %Medicao/Contrato' = round(DIVIDE(SUM('C3 - MEDIÇÕES'[VALOR]),SUM('C3 -  CONTRATOS'[VALOR])),4)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 8a2770bd-860f-4670-a90f-e4ab851c8fe6

	measure 'C3 - Tabela - QuantidadeContrato-Medicao' = round(sum('C3 -  CONTRATOS'[QUANTIDADE])-sum('C3 - MEDIÇÕES'[QUANTIDADE]),2)
		lineageTag: d65cef5a-621e-40b8-a8f9-fef1baa114cf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'C3 - Tabela - ValorContrato-Medicao' = round(sum('C3 -  CONTRATOS'[VALOR])-sum('C3 - MEDIÇÕES'[VALOR]),2)
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 19f389b7-1ffc-49f2-86bf-74abc09e1572

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure Medida = 40
		formatString: 0
		lineageTag: 29a611f9-35f6-444a-b9e9-74cf44a18783

	measure 'C3 - Cartao - SaldoContratual' = [C3 - Cartao - ValorEmpenhado]-[C3 - Cartao - ValorComprometido]
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 0d59df29-8bb7-4f85-bddb-6a8cfeda59e3

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'C3 - Cartao - ValorEmContratacao' = IF(CALCULATE(sum('C3 - CONTRATO CONTROLE'[VALOR CONTRATUAL COM ADITIVO]),FILTER('C3 - CONTRATO CONTROLE','C3 - CONTRATO CONTROLE'[STATUS DO CONTRATO]="EM ELABORAÇÃO"))=0,0,CALCULATE(sum('C3 - CONTRATO CONTROLE'[VALOR CONTRATUAL COM ADITIVO]),FILTER('C3 - CONTRATO CONTROLE','C3 - CONTRATO CONTROLE'[STATUS DO CONTRATO]="EM ELABORAÇÃO")))
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: f1de860d-755e-45fc-826a-ae47b5a43736

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column zzzzzzzz
		dataType: string
		lineageTag: bdd22fb7-d088-41d1-9e6c-c8ca0dc91935
		summarizeBy: none
		sourceColumn: zzzzzzzz

		annotation SummarizationSetBy = Automatic

	partition '@ @ MEDIDAS' = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Coluna 1", type text}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado",{{"Coluna 1", "zzzzzzzz"}})
				in
				    #"Colunas Renomeadas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

