table '@ @ NOME GERENCIA'
	lineageTag: f311eaf0-49fd-428e-af00-837a64fb2601

	column GerenciaExtenso
		dataType: string
		lineageTag: 3d4d0370-a2a4-4836-b374-cffcf584d7e7
		summarizeBy: none
		sourceColumn: GerenciaExtenso

		annotation SummarizationSetBy = Automatic

	column GerenciaAbreviado
		dataType: string
		lineageTag: 88d52bab-d20c-4867-bd75-e654deef5a7e
		summarizeBy: none
		sourceColumn: GerenciaAbreviado

		annotation SummarizationSetBy = Automatic

	partition '@ @ NOME GERENCIA' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("bc3BCYAwEETRVkLONjHqEhbMJi7rSWzGo2BVacyoF1HP/w0zzz6Qlk06huuTCwrpyTc+BPVL86wDW9KyCuHMg71yHWcoyt7CkYsQ43Ei1kvn+K8FGULxNvlrjMnKdlarf8sB", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [GerenciaExtenso = _t, GerenciaAbreviado = _t]),
				    #"Replaced Value" = Table.ReplaceValue(Source,"GERÊNCIA DO GRANDE","GGR - GRANDE",Replacer.ReplaceText,{"GerenciaExtenso"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","GERÊNCIA LITORÂNEA","GLT - LITORÂNEA",Replacer.ReplaceText,{"GerenciaExtenso"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","GERÊNCIA DO PARAÍBA E MANTIQUEIRA","GPM - PARAÍBA E MANTIQUEIRA",Replacer.ReplaceText,{"GerenciaExtenso"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","GERÊNCIA DO PARANAPANEMA","GPP - PARANAPANEMA",Replacer.ReplaceText,{"GerenciaExtenso"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","GERÊNCIA DO TIETÊ","GTT - TIETÊ",Replacer.ReplaceText,{"GerenciaExtenso"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Replaced Value4",{{"GerenciaExtenso", type text}, {"GerenciaAbreviado", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

