table 'C2 - STATUS'
	lineageTag: 1c3fa3f7-a4d4-4b2d-8101-5acbc88aabcc

	column BACIA
		dataType: string
		lineageTag: b53a43dd-0493-41af-82f8-4d01d5837bf0
		summarizeBy: none
		sourceColumn: BACIA

		annotation SummarizationSetBy = Automatic

	column MUNICÍPIO
		dataType: string
		lineageTag: dc3a6edb-5053-419c-a771-1ce1f2863d00
		summarizeBy: none
		sourceColumn: MUNICÍPIO

		annotation SummarizationSetBy = Automatic

	column 'CURSO D´ÁGUA'
		dataType: string
		lineageTag: 9fbf1f66-95d9-45b6-875b-f9898f154723
		summarizeBy: none
		sourceColumn: CURSO D´ÁGUA

		annotation SummarizationSetBy = Automatic

	column 'CORPO HÍDRICO / TRECHO'
		dataType: string
		lineageTag: 97ae1855-a53d-4170-9dfe-b06d6bda6b5b
		summarizeBy: none
		sourceColumn: CORPO HÍDRICO / TRECHO

		annotation SummarizationSetBy = Automatic

	column INÍCIO
		dataType: dateTime
		formatString: dd/mm/yy
		lineageTag: 64c94bef-cc0f-42aa-8e9b-3e13cc51c716
		summarizeBy: none
		sourceColumn: INÍCIO

		variation Variation
			isDefault
			relationship: 96d9b98d-4b12-4178-8aea-ee2fc18adbf9
			defaultHierarchy: LocalDateTable_c6d9a90e-c8c9-4a78-a923-fb60ed6c296f.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column TÉRMINO
		dataType: dateTime
		formatString: dd/mm/yy
		lineageTag: ebe172d7-40a2-4eb4-a271-b4130d4eab46
		summarizeBy: none
		sourceColumn: TÉRMINO

		variation Variation
			isDefault
			relationship: 62f0a8ed-9dc8-4d57-b90a-ed31a66f88b2
			defaultHierarchy: LocalDateTable_da1d6ae4-704c-4947-9b08-9046fda37cfb.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column 'STATUS DO TRECHO'
		dataType: string
		lineageTag: 6e501878-bd6b-49f0-8406-00d3fcaa9b1c
		summarizeBy: none
		sourceColumn: STATUS DO TRECHO

		annotation SummarizationSetBy = Automatic

	column 'REGIÃO ADMINISTRATIVA'
		dataType: string
		lineageTag: dcd4e439-8604-4e1a-917b-1b1db4eb1d68
		summarizeBy: none
		sourceColumn: REGIÃO ADMINISTRATIVA

		annotation SummarizationSetBy = Automatic

	column DIRETORIA = concatenate("D", 'C2 - STATUS'[BACIA])
		lineageTag: a8ae04c8-930e-4bac-91ce-873d2fccca64
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'ATESTADO DE CONCLUSÃO'
		dataType: string
		lineageTag: b3408bfd-b287-4085-b931-804c5681ccec
		summarizeBy: none
		sourceColumn: ATESTADO DE CONCLUSÃO

		annotation SummarizationSetBy = Automatic

	column 'VALOR POR MUNICÍPIO (R$)'
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: caebeb89-24ea-43dc-a4b7-60977ff9bf27
		summarizeBy: sum
		sourceColumn: VALOR POR MUNICÍPIO (R$)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column EXTENSÃO
		dataType: double
		lineageTag: e8d166b1-e25b-4564-bee3-95ac4d2d8282
		summarizeBy: sum
		sourceColumn: EXTENSÃO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'VOLUME MEDIÇÃO'
		dataType: double
		lineageTag: 580d4be1-e278-419d-afe9-22838b491d83
		summarizeBy: sum
		sourceColumn: VOLUME MEDIÇÃO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LON_I
		dataType: double
		lineageTag: 1492d931-6fe8-4c23-8857-66e90c2c15ac
		dataCategory: Longitude
		summarizeBy: none
		sourceColumn: LON_I

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LAT_I
		dataType: double
		lineageTag: 730a0d7b-eb87-4385-afa7-4cffadd6424b
		dataCategory: Latitude
		summarizeBy: none
		sourceColumn: LAT_I

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CONTRATO
		dataType: int64
		formatString: 0
		lineageTag: e0426d17-7c64-44a7-984a-e09457afbb51
		summarizeBy: sum
		sourceColumn: CONTRATO

		annotation SummarizationSetBy = Automatic

	column 'ID CONTRATO' = CONCATENATE('C2 - STATUS'[DIRETORIA],'C2 - STATUS'[CONTRATO])
		lineageTag: 30ab64ce-e2be-4b80-986f-1ce6407e8b2f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'ID MUNICIPIO' = CONCATENATE('C2 - STATUS'[MUNICÍPIO], 'C2 - STATUS'[CONTRATO])
		lineageTag: 7dbb671b-452c-42d0-a883-8d9895a008cc
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'CONTRATO FILTRO' = CONCATENATE("CONTRATO ", 'C2 - STATUS'[CONTRATO])
		lineageTag: eab14a79-fb03-4f45-83fe-c340ac70099b
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column POPULACAO = SELECTCOLUMNS(FILTER('@ @ MUNICÍPIOS BRASIL','@ @ MUNICÍPIOS BRASIL'[MUNICIPIO]='C2 - STATUS'[MUNICÍPIO]),'@ @ MUNICÍPIOS BRASIL'[POPULAÇÃO])
		formatString: #,0
		lineageTag: 8d3f7bdc-84f5-41a1-ae96-75e97591f613
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Column16
		dataType: string
		lineageTag: 4e4a34c5-fce8-464b-bfc3-2518e665c86c
		summarizeBy: none
		sourceColumn: Column16

		annotation SummarizationSetBy = Automatic

	partition 'C2 - STATUS' = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(Web.Contents("https://revitalizarrv.sharepoint.com/SupervisaoObras/DESASSOREAMENTO/2%C2%BA%20Ciclo/2%20-%20Arquivos%20de%20Controle/Consolidado%20Corpo%20Hidrico%20-%20Status.xlsx"), null, true),
				    #"STATUS OCULTA_Sheet" = Fonte{[Item="STATUS OCULTA",Kind="Sheet"]}[Data],
				    #"Linhas Filtradas" = Table.SelectRows(#"STATUS OCULTA_Sheet", each ([Column2] <> null)),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Linhas Filtradas",{"Column1", "Column4", "Column5", "Column12", "Column17", "Column18", "Column19", "Column20", "Column21", "Column22", "Column23", "Column26", "Column27", "Column29"}),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Colunas Removidas", [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"BACIA", type text}, {"MUNICÍPIO", type text}, {"CURSO D´ÁGUA", type text}, {"CORPO HÍDRICO / TRECHO", type text}, {"STATUS DO TRECHO", type text}, {"REGIÃO ADMINISTRATIVA", type text}, {"* EXTENSÃO #(lf) (m)", type number}, {"VOLUME MEDIÇÃO#(lf)(m³)", type number}, {"ATESTADO DE CONCLUSÃO", type text}, {"VALOR POR MUNICÍPIO#(lf) (R$)", Currency.Type}, {"CONTRATO", Int64.Type}}),
				    #"Tipo Alterado com Localidade" = Table.TransformColumnTypes(#"Tipo Alterado", {{"INÍCIO", type date}}, "pt-BR"),
				    #"Tipo Alterado com Localidade1" = Table.TransformColumnTypes(#"Tipo Alterado com Localidade", {{"TÉRMINO", type date}}, "pt-BR"),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado com Localidade1",{{"* EXTENSÃO #(lf) (m)", "EXTENSÃO"}, {"VOLUME MEDIÇÃO#(lf)(m³)", "VOLUME MEDIÇÃO"}}),
				    #"Tipo Alterado com Localidade2" = Table.TransformColumnTypes(#"Colunas Renomeadas", {{"VALOR POR MUNICÍPIO#(lf) (R$)", Currency.Type}}, "pt-BR"),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Tipo Alterado com Localidade2",{{"LON_I", type number}, {"LAT_I", type number}})
				in
				    #"Tipo Alterado1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

