table 'C2 - ATA'
	lineageTag: 499edabe-6c35-48a9-8080-b79e5bdc7912

	column BACIA
		dataType: string
		lineageTag: 02c457e0-2431-45c2-b460-33944268c9ec
		summarizeBy: none
		sourceColumn: BACIA

		annotation SummarizationSetBy = Automatic

	column LOTE
		dataType: int64
		formatString: 0
		lineageTag: ff2ec8bc-c384-4cfc-90ca-4ae8feace3dc
		summarizeBy: none
		sourceColumn: LOTE

		annotation SummarizationSetBy = Automatic

	column DIRETORIA
		dataType: string
		lineageTag: 15648f0e-c530-4874-bb5c-4a2088d93cac
		summarizeBy: none
		sourceColumn: DIRETORIA

		annotation SummarizationSetBy = Automatic

	column VALOR-ATA
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 926899c1-ef74-4fb7-acac-3834ca726adb
		summarizeBy: none
		sourceColumn: VALOR-ATA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column VALOR-CONTRATO
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: a4932fd5-52c1-4ab2-8666-34558ebb227e
		summarizeBy: none
		sourceColumn: VALOR-CONTRATO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column ADITIVO-CONTRATO
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: e0fd20a1-a5ac-478b-ab09-af6aa0ee7182
		summarizeBy: none
		sourceColumn: ADITIVO-CONTRATO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column 'VALOR TOTAL-CONTRATO'
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: f1ff14fd-963a-46ce-b056-f0860c61969f
		summarizeBy: none
		sourceColumn: VALOR TOTAL-CONTRATO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	partition 'C2 - ATA' = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(Web.Contents("https://revitalizarrv.sharepoint.com/SupervisaoObras/DESASSOREAMENTO/2%C2%BA%20Ciclo/2%20-%20Arquivos%20de%20Controle/Consolidado%20Corpo%20Hidrico%20-%20Status.xlsx"), null, true),
				    #"VALOR DA ATA_Sheet" = Fonte{[Item="VALOR DA ATA",Kind="Sheet"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"VALOR DA ATA_Sheet",{{"Column1", type text}, {"Column2", type any}, {"Column3", type text}, {"Column4", type any}, {"Column5", type any}, {"Column6", type any}, {"Column7", type any}, {"Column8", type any}, {"Column9", type any}, {"Column10", type any}, {"Column11", type any}, {"Column12", type any}, {"Column13", type any}, {"Column14", type text}, {"Column15", type any}, {"Column16", type any}, {"Column17", type any}, {"Column18", type any}, {"Column19", type any}, {"Column20", type any}, {"Column21", type any}, {"Column22", type any}, {"Column23", type any}, {"Column24", type any}, {"Column25", type any}, {"Column26", type any}}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Tipo Alterado", each ([Column3] <> null)),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Linhas Filtradas", [PromoteAllScalars=true]),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Cabeçalhos Promovidos",{{"Column1", "BACIA"}}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Colunas Renomeadas",{{"BACIA", type text}, {"Lote ", Int64.Type}, {"Diretoria", type text}, {"ATA de Registro de Preços (R$)", Currency.Type}, {"Valor Contratado (R$)", Currency.Type}, {"Aditivos (R$)", Currency.Type}, {"Valor Total do Contrato (R$)", Currency.Type}, {"Saldo da ATA (R$)", type number}, {"% Contratado", type number}, {"Column10", type any}, {"Valor Medido (R$)", type number}, {"% Medida dos contratos ", type number}, {"Saldo dos Contratos", type number}, {"Comentários ", type text}, {"Column15", type any}, {"Column16", type any}, {"Column17", type any}, {"Column18", type any}, {"Column19", type any}, {"Column20", type any}, {"Column21", type any}, {"Column22", type any}, {"Column23", type any}, {"Column24", type any}, {"Column25", type any}, {"Column26", type any}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado1",{"% Contratado", "Column10", "Valor Medido (R$)", "% Medida dos contratos ", "Saldo dos Contratos", "Comentários ", "Column15", "Column16", "Column17", "Column18", "Column19", "Column20", "Column21", "Column22", "Column23", "Column24", "Column25", "Saldo da ATA (R$)", "Column26"}),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Colunas Removidas",{{"Lote ", "LOTE"}, {"Diretoria", "DIRETORIA"}, {"ATA de Registro de Preços (R$)", "VALOR-ATA"}, {"Valor Contratado (R$)", "VALOR-CONTRATO"}, {"Aditivos (R$)", "ADITIVO-CONTRATO"}, {"Valor Total do Contrato (R$)", "VALOR TOTAL-CONTRATO"}}),
				    #"Tipo Alterado com Localidade" = Table.TransformColumnTypes(#"Colunas Renomeadas1", {{"VALOR-ATA", Currency.Type}}, "pt-BR"),
				    #"Tipo Alterado com Localidade1" = Table.TransformColumnTypes(#"Tipo Alterado com Localidade", {{"VALOR-CONTRATO", Currency.Type}}, "pt-BR"),
				    #"Tipo Alterado com Localidade2" = Table.TransformColumnTypes(#"Tipo Alterado com Localidade1", {{"ADITIVO-CONTRATO", Currency.Type}}, "pt-BR"),
				    #"Tipo Alterado com Localidade3" = Table.TransformColumnTypes(#"Tipo Alterado com Localidade2", {{"VALOR TOTAL-CONTRATO", Currency.Type}}, "pt-BR")
				in
				    #"Tipo Alterado com Localidade3"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

