table 'C2 - MEDIÇÃO COM VOLUME'
	lineageTag: d21295e6-baab-429d-8e79-ccd84d23ad06

	column 'BACIA '
		dataType: string
		lineageTag: 6f4fd4e5-9da3-43db-ad0a-ff3da4c951ee
		summarizeBy: none
		sourceColumn: "BACIA "

		annotation SummarizationSetBy = Automatic

	column CONTRATO
		dataType: int64
		formatString: 0
		lineageTag: 8035db55-0a89-4735-b160-cbf0c468db1e
		summarizeBy: none
		sourceColumn: CONTRATO

		annotation SummarizationSetBy = User

	column MEDIÇÃO
		dataType: int64
		formatString: 0
		lineageTag: bb7d732c-0bb3-44b0-aa04-deddf9c7ddfd
		summarizeBy: none
		sourceColumn: MEDIÇÃO

		annotation SummarizationSetBy = User

	column MUNICÍPIO
		dataType: string
		lineageTag: 406bd374-0d39-4115-9c5c-3cd5f73a1844
		summarizeBy: none
		sourceColumn: MUNICÍPIO

		annotation SummarizationSetBy = Automatic

	column 'VOLUME MEDIDO'
		dataType: double
		lineageTag: 7504d308-3720-447c-9d03-39941a632ea6
		summarizeBy: sum
		sourceColumn: VOLUME MEDIDO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'VALOR MEDIDO'
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: b870e89e-ce91-462b-aa17-7448aa113822
		summarizeBy: sum
		sourceColumn: VALOR MEDIDO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column 'MÊS REF'
		dataType: dateTime
		formatString: dd/mm/yy
		lineageTag: 865ed42c-e8cd-4e7d-ba25-c412943ff436
		summarizeBy: none
		sourceColumn: MÊS REF

		variation Variation
			isDefault
			relationship: b427bd67-eed8-4da5-9a4b-586a346b5686
			defaultHierarchy: LocalDateTable_61734ee7-6ee4-400a-8ec1-2cbe5a1e6afb.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column 'MÊS PAGO'
		dataType: dateTime
		formatString: mmm/yy
		lineageTag: 2ad9d4ea-624f-46ed-aa5f-fb52d948bdb9
		summarizeBy: none
		sourceColumn: MÊS PAGO

		variation Variation
			isDefault
			relationship: 737f2d80-17ea-4141-884a-2c9e7688d805
			defaultHierarchy: LocalDateTable_0c389099-447f-4339-85d4-013e19fe61f0.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column 'NOMENCLATURA mes/ano' = FORMAT(Date('C2 - MEDIÇÃO COM VOLUME'[MÊS PAGO].[Ano],'C2 - MEDIÇÃO COM VOLUME'[MÊS PAGO].[MonthNo],01),"mmm/yy")
		lineageTag: e8a48d9d-dbe6-4c08-bfb6-c8702b2e5844
		summarizeBy: none
		sortByColumn: 'MÊS PAGO SEM DATA'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column DIRETORIA = CONCATENATE("D", 'C2 - MEDIÇÃO COM VOLUME'[BACIA ])
		lineageTag: db7b4aee-ec25-4e1d-92de-3b694315c922
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'ANO PAGAMENTO' = DATE('C2 - MEDIÇÃO COM VOLUME'[MÊS PAGO].[Ano],01,01)
		formatString: yyyy
		lineageTag: 1502969f-466e-4299-8b23-fa112a42bf64
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 8d8d07ae-0aa9-4be3-b99e-ada4bfac4b26
			defaultHierarchy: LocalDateTable_ea1a7e55-365d-4bc4-b714-2091420fa574.'Hierarquia de datas'

		changedProperty = DataType

		annotation SummarizationSetBy = User

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column 'MES PAGAMENTO' = DATE(2000,'C2 - MEDIÇÃO COM VOLUME'[MÊS PAGO].[MonthNo],01)
		dataType: dateTime
		formatString: mmmm
		lineageTag: 00c2a1f6-b0ba-473d-a411-5ec270c1f8e8
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 0b6ca021-dd83-4aa2-890c-7a7fee73f507
			defaultHierarchy: LocalDateTable_6f2fa2aa-c8ac-48f7-951d-b24a2bb3269b.'Hierarquia de datas'

		changedProperty = SortByColumn

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column 'MÊS PAGO SEM DATA' = DATE('C2 - MEDIÇÃO COM VOLUME'[MÊS PAGO].[Ano],'C2 - MEDIÇÃO COM VOLUME'[MÊS PAGO].[MonthNo],01)
		formatString: dd/mm/yyy
		lineageTag: 89d3bb16-1737-42b0-9a23-0179655e2efe
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 510b6e90-41cd-4cf6-8f58-4e0f17886d77
			defaultHierarchy: LocalDateTable_05c30dd2-19bf-43f5-9082-a948f4b480cd.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isCustom":true}

	column 'ID CONTRATO' = CONCATENATE('C2 - MEDIÇÃO COM VOLUME'[DIRETORIA],'C2 - MEDIÇÃO COM VOLUME'[CONTRATO])
		lineageTag: 84a463b2-6079-48d8-ba37-076a6f07e58d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'ID MUNICIPIO' = CONCATENATE('C2 - MEDIÇÃO COM VOLUME'[MUNICÍPIO],'C2 - MEDIÇÃO COM VOLUME'[CONTRATO])
		lineageTag: 418de0ac-7840-4dd5-991d-6b3333df370c
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'C2 - MEDIÇÃO COM VOLUME' = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(Web.Contents("https://revitalizarrv.sharepoint.com/SupervisaoObras/DESASSOREAMENTO/2%C2%BA%20Ciclo/2%20-%20Arquivos%20de%20Controle/CUSTO-MEDI%C3%87%C3%95ES%20COM%20Volume.xlsx"), null, true),
				    NF_Sheet = Fonte{[Item="NF",Kind="Sheet"]}[Data],
				    #"Colunas Removidas" = Table.RemoveColumns(NF_Sheet,{"Column10", "Column11", "Column12", "Column13", "Column14", "Column15", "Column16", "Column17", "Column18", "Column19", "Column20", "Column21", "Column22", "Column23", "Column24", "Column25", "Column26", "Column27", "Column28", "Column29", "Column30", "Column9"}),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Colunas Removidas", [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"BACIA ", type text}, {"CONTRATO", Int64.Type}, {"MEDIÇÃO", Int64.Type}, {"MUNICÍPIO", type text}, {"VOLUME (m³)", type number}, {"VALOR", Currency.Type}, {"MÊS REF", type date}, {"MÊS PAGO", type date}}),
				    #"Tipo Alterado com Localidade" = Table.TransformColumnTypes(#"Tipo Alterado", {{"MÊS REF", type date}}, "pt-BR"),
				    #"Tipo Alterado com Localidade1" = Table.TransformColumnTypes(#"Tipo Alterado com Localidade", {{"MÊS PAGO", type date}}, "pt-BR"),
				    #"Linhas Filtradas" = Table.SelectRows(#"Tipo Alterado com Localidade1", each ([#"BACIA "] <> null)),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Linhas Filtradas",{{"VOLUME (m³)", "VOLUME MEDIDO"}, {"VALOR", "VALOR MEDIDO"}}),
				    #"Tipo Alterado com Localidade2" = Table.TransformColumnTypes(#"Colunas Renomeadas", {{"VALOR MEDIDO", Currency.Type}}, "pt-BR")
				in
				    #"Tipo Alterado com Localidade2"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

