table 'C3 - ATA CONTROLE'
	lineageTag: e14cf194-c81a-43af-84e4-02c112dfb8b1

	column REFERÊNCIA
		dataType: string
		lineageTag: 3cf3f125-3850-49ec-95a0-aba2108da767
		summarizeBy: none
		sourceColumn: REFERÊNCIA

		annotation SummarizationSetBy = Automatic

	column 'VALOR TOTAL'
		dataType: decimal
		lineageTag: 535e0478-9e98-4b2d-806d-d35155866d3a
		summarizeBy: sum
		sourceColumn: VALOR TOTAL

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'VALOR UTILIZADO'
		dataType: decimal
		lineageTag: e61a0802-4bc7-49f4-b881-2195019aeda0
		summarizeBy: sum
		sourceColumn: VALOR UTILIZADO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SALDO
		dataType: decimal
		lineageTag: 4cc65d2e-7551-4548-a22a-1209dbce395f
		summarizeBy: sum
		sourceColumn: SALDO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'PERCENTUAL UTILIZADO'
		dataType: double
		lineageTag: 2f6767ec-1d7b-4411-b0db-e6a59fa2a018
		summarizeBy: sum
		sourceColumn: PERCENTUAL UTILIZADO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VIGÊNCIA
		dataType: dateTime
		formatString: Long Date
		lineageTag: ac97df62-82e2-4e8c-9ea4-295e473ef5c6
		summarizeBy: none
		sourceColumn: VIGÊNCIA

		variation Variation
			isDefault
			relationship: e588f468-c315-4b6b-8e12-3d8e710b35a0
			defaultHierarchy: LocalDateTable_0400741a-3ba0-42ef-ba35-6e0ac5fc3b08.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Nº ATA'
		dataType: string
		lineageTag: 5f87aeab-5ad1-444d-af95-c3341ee02a9d
		summarizeBy: none
		sourceColumn: Nº ATA

		annotation SummarizationSetBy = Automatic

	column GERÊNCIA
		dataType: string
		lineageTag: c70fa091-c182-4e42-b084-f96358535cfd
		summarizeBy: none
		sourceColumn: GERÊNCIA

		annotation SummarizationSetBy = Automatic

	column DIVISÃO
		dataType: string
		lineageTag: 0915a4d3-1ae1-475f-b543-432affd3ab76
		summarizeBy: none
		sourceColumn: DIVISÃO

		annotation SummarizationSetBy = Automatic

	partition 'C3 - ATA CONTROLE' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://revitalizarrv.sharepoint.com/SupervisaoObras/DESASSOREAMENTO/3%C2%BA%20Ciclo/2%20-%20Arquivos%20de%20Controle/CONTROLE%20QUANTITATIVOS.xlsx"), null, true),
				    C.ATA_Sheet = Source{[Item="C.ATA",Kind="Sheet"]}[Data],
				    #"Linhas Filtradas" = Table.SelectRows(C.ATA_Sheet, each ([Column3] <> null)),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Linhas Filtradas", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"REFERÊNCIA", type text}, {"VALOR TOTAL", type number}, {"VALOR UTILIZADO", type number}, {"SALDO", type number}, {"PERCENTUAL UTILIZADO", type number}, {"VIGÊNCIA", type date}, {"Nº ATA", type text}}),
				    #"Changed Type with Locale" = Table.TransformColumnTypes(#"Changed Type", {{"VALOR TOTAL", Currency.Type}}, "pt-BR"),
				    #"Changed Type with Locale1" = Table.TransformColumnTypes(#"Changed Type with Locale", {{"VALOR UTILIZADO", Currency.Type}}, "pt-BR"),
				    #"Changed Type with Locale2" = Table.TransformColumnTypes(#"Changed Type with Locale1", {{"SALDO", Currency.Type}}, "pt-BR"),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type with Locale2",{{"PERCENTUAL UTILIZADO", Percentage.Type}}),
				    #"Changed Type with Locale3" = Table.TransformColumnTypes(#"Changed Type1", {{"VIGÊNCIA", type date}}, "pt-BR"),
				    #"Linhas Filtradas1" = Table.SelectRows(#"Changed Type with Locale3", each ([REFERÊNCIA] <> null))
				in
				    #"Linhas Filtradas1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

