table 'C3 - MEDIÇÕES'
	lineageTag: a9a02339-4ee2-471c-aa1c-ab892f2bec97

	column BACIA
		dataType: string
		lineageTag: c466e21e-2425-4b47-8221-a7dc0ddf37a3
		summarizeBy: none
		sourceColumn: BACIA

		annotation SummarizationSetBy = Automatic

	column CONTRATO
		dataType: int64
		formatString: 0
		lineageTag: 28aa4d5d-5f4f-47e3-ae23-fe6db18936d6
		summarizeBy: none
		sourceColumn: CONTRATO

		annotation SummarizationSetBy = User

	column MUNICÍPIO
		dataType: string
		lineageTag: 2de46e78-a6fe-4929-9703-e169c61931a3
		summarizeBy: none
		sourceColumn: MUNICÍPIO

		annotation SummarizationSetBy = Automatic

	column 'CORPO HÍDRICO'
		dataType: string
		lineageTag: 93b4c786-529b-4cc2-a682-42c73be04cf1
		summarizeBy: none
		sourceColumn: CORPO HÍDRICO

		annotation SummarizationSetBy = Automatic

	column QUANTIDADE
		dataType: double
		lineageTag: f2151547-01c0-43f4-989f-d9ebd6af9b42
		summarizeBy: sum
		sourceColumn: QUANTIDADE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'MÊS PAGO'
		dataType: dateTime
		formatString: dd/mm/yy
		lineageTag: 6dbd1d36-5fa4-4ccb-8e49-20b222f66297
		summarizeBy: none
		sourceColumn: MÊS PAGO

		variation Variation
			isDefault
			relationship: f53db75f-9e20-4596-92ca-e857eb8d4b92
			defaultHierarchy: LocalDateTable_0d5622fa-acd2-4a53-b719-49be8aa08273.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column VALOR
		dataType: decimal
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 71a6984a-742c-4023-9ed3-0f62690e5e22
		summarizeBy: sum
		sourceColumn: VALOR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column DIRETORIA = CONCATENATE("D",'C3 - MEDIÇÕES'[BACIA])
		lineageTag: c6691da8-78d5-4951-90bd-b92a5f5e2990
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column ITEM
		dataType: string
		lineageTag: bc9ec23b-3c9d-4d43-b2b0-b66c6757ff39
		summarizeBy: none
		sourceColumn: ITEM
		sortByColumn: ItemFiltro

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'FILTRO MES' = 'C3 - MEDIÇÕES'[MÊS PAGO].[Mês]
		lineageTag: 85602c02-36c0-48f4-ae4e-23a46b866434
		summarizeBy: none
		sortByColumn: 'MÊS NÚMERO'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'FILTRO ANO' = 'C3 - MEDIÇÕES'[MÊS PAGO].[Ano]
		formatString: 0
		lineageTag: ede3bc92-fecd-4409-8c24-03a98dedaa6c
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'MÊS REFERÊNCIA'
		dataType: dateTime
		formatString: mmm/yyyy
		lineageTag: 7910139a-2925-4dc7-a980-9473499984f0
		summarizeBy: none
		sourceColumn: MÊS REFERÊNCIA

		variation Variation
			isDefault
			relationship: 2ecf4676-f456-4f03-bb1a-04853a73507e
			defaultHierarchy: LocalDateTable_31cebc64-7ab1-4578-bf76-bd4d41fce5e0.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column 'MÊS NÚMERO' = 'C3 - MEDIÇÕES'[MÊS PAGO].[MonthNo]
		formatString: 0
		lineageTag: 1e69a958-f2fd-4d01-bdb6-e581b1108e9b
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'NOMENCLATURA mes/ano' = FORMAT(DATE('C3 - MEDIÇÕES'[MÊS PAGO].[Ano],'C3 - MEDIÇÕES'[MÊS PAGO].[MonthNo],01),"mmm/yy")
		lineageTag: fbb2f218-7db0-4779-a3bf-96178d23e354
		summarizeBy: none
		sortByColumn: 'MÊS NÚMERO'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'VOLUME MEDIDO' = IF(OR(OR(OR('C3 - MEDIÇÕES'[ITEM]="6.1",'C3 - MEDIÇÕES'[ITEM]="6.2"),'C3 - MEDIÇÕES'[ITEM]="6.3"),'C3 - MEDIÇÕES'[ITEM]="6.4"),'C3 - MEDIÇÕES'[QUANTIDADE],0)
		lineageTag: b883d520-3fdd-4b23-9446-f048ab102df8
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column REFERÊNCIA
		dataType: string
		lineageTag: 266a6f42-6f6f-447e-b028-8c21d34afa68
		summarizeBy: none
		sourceColumn: REFERÊNCIA

		annotation SummarizationSetBy = Automatic

	column STATUS
		dataType: string
		lineageTag: 232b3af1-f64d-48fc-9b8f-861ed9f9aff9
		summarizeBy: none
		sourceColumn: STATUS

		annotation SummarizationSetBy = Automatic

	column ItemFiltro
		dataType: double
		lineageTag: fd307895-680a-4207-a1e9-20aee0616617
		summarizeBy: sum
		sourceColumn: ItemFiltro

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column GEOCODIGO = SELECTCOLUMNS(FILTER('@ @ MUNICÍPIOS BRASIL','@ @ MUNICÍPIOS BRASIL'[MUNICIPIO]='C3 - MEDIÇÕES'[MUNICÍPIO]),'@ @ MUNICÍPIOS BRASIL'[GEOCODIGO])
		formatString: 0
		lineageTag: e9897322-db5c-4467-8518-a2a3c82b3074
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column ID_OS = CONCATENATE(CONCATENATE(CONCATENATE('C3 - MEDIÇÕES'[REFERÊNCIA],'C3 - MEDIÇÕES'[CONTRATO]),'C3 - MEDIÇÕES'[Nº OS]),'C3 - MEDIÇÕES'[GEOCODIGO])
		lineageTag: d288020d-c345-437b-9aaf-87b329080c46
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column ID_TRECHO = CONCATENATE('C3 - MEDIÇÕES'[ID_OS],SUBSTITUTE('C3 - MEDIÇÕES'[CORPO HÍDRICO]," ",""))
		lineageTag: 1423b1d9-8321-414e-8fcf-0827e1290623
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Nº OS' = SELECTCOLUMNS(FILTER('C3 - STATUS',AND('C3 - MEDIÇÕES'[CORPO HÍDRICO]='C3 - STATUS'[CORPO HÍDRICO / TRECHO],'C3 - STATUS'[STATUS DO TRECHO]<>"AGUARDANDO O.S.")),"N° OS",'C3 - STATUS'[Nº OS])
		lineageTag: 0e4678d9-bfd6-4fee-8ff0-eba9ca4ea7e0
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'C3 - MEDIÇÕES' = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(Web.Contents("https://revitalizarrv.sharepoint.com/SupervisaoObras/DESASSOREAMENTO/3%C2%BA%20Ciclo/2%20-%20Arquivos%20de%20Controle/CONTROLE%20QUANTITATIVOS.xlsx"), null, true),
				    MEDIÇÕES_Sheet = Fonte{[Item="MEDIÇÕES",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(MEDIÇÕES_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"DIRETORIA", type text}, {"CONTRATO", Int64.Type}, {"MUNICÍPIO", type text}, {"CORPO HÍDRICO", type text}, {"ITEM", type text}, {"DESCRIÇÃO", type text}, {"QUANTIDADE", type number}, {"DATA ATUALIZAÇÃO", type date}, {"MÊS REFERÊNCIA", type date}, {"MÊS PAGO", type date}, {"STATUS", type text}, {"USUÁRIO", type text}, {"VALOR MEDIDO", type number}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"USUÁRIO", "DATA ATUALIZAÇÃO", "DESCRIÇÃO"}),
				    #"Tipo Alterado com Localidade" = Table.TransformColumnTypes(#"Colunas Removidas", {{"MÊS PAGO", type date}}, "pt-BR"),
				    #"Tipo Alterado com Localidade1" = Table.TransformColumnTypes(#"Tipo Alterado com Localidade", {{"MÊS REFERÊNCIA", type date}}, "pt-BR"),
				    #"Tipo Alterado com Localidade2" = Table.TransformColumnTypes(#"Tipo Alterado com Localidade1", {{"VALOR MEDIDO", Currency.Type}}, "pt-BR"),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado com Localidade2",{{"DIRETORIA", "BACIA"}}),
				    Custom1 = Table.DuplicateColumn(#"Colunas Renomeadas","ITEM","ItemFiltro"),
				    Custom2 = Table.SplitColumn(Custom1,"ItemFiltro",Splitter.SplitTextByPositions({0,1,2})),
				    Custom3 = Table.ReplaceValue(Custom2, each [ItemFiltro.3], each if [ItemFiltro.3]<>"10" then Text.Combine({"0",[ItemFiltro.3]}) else [ItemFiltro.3], Replacer.ReplaceValue, {"ItemFiltro.3"}),
				    Custom4 = Table.CombineColumns(Custom3,{"ItemFiltro.1","ItemFiltro.3"},Combiner.CombineTextByDelimiter(",", QuoteStyle.None), "ItemFiltro"),
				    #"Removed Columns" = Table.RemoveColumns(Custom4,{"ItemFiltro.2"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns",{{"ItemFiltro", type number}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"VALOR MEDIDO", "VALOR"}}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Renamed Columns", each ([CORPO HÍDRICO] <> null))
				in
				    #"Linhas Filtradas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

