table 'C3 - STATUS'
	lineageTag: 745bb8cc-b96b-4c8e-970d-b79f6c4e8da0

	column BACIA
		dataType: string
		lineageTag: 4ae80a5d-382d-45f9-8c48-890b2db16163
		summarizeBy: none
		sourceColumn: BACIA

		annotation SummarizationSetBy = Automatic

	column CONTRATO
		dataType: int64
		formatString: 0
		lineageTag: 3ede24a2-6c1e-4a05-97fb-e67862f3bf2a
		summarizeBy: sum
		sourceColumn: CONTRATO

		annotation SummarizationSetBy = Automatic

	column 'REGIÃO ADMINISTRATIVA'
		dataType: string
		lineageTag: b0464c43-fe00-4329-8620-92207c5cf7c3
		summarizeBy: none
		sourceColumn: REGIÃO ADMINISTRATIVA

		annotation SummarizationSetBy = Automatic

	column MUNICÍPIO
		dataType: string
		lineageTag: 694d2fdf-87e9-46c2-8247-4811708d3fe6
		summarizeBy: none
		sourceColumn: MUNICÍPIO

		annotation SummarizationSetBy = Automatic

	column 'CURSO D´ÁGUA'
		dataType: string
		lineageTag: 4c1ce049-69d2-4865-bb6e-1bcdef29229d
		summarizeBy: none
		sourceColumn: CURSO D´ÁGUA

		annotation SummarizationSetBy = Automatic

	column 'CORPO HÍDRICO / TRECHO'
		dataType: string
		lineageTag: bfde610b-ea9f-4176-bb71-01329819ecd6
		summarizeBy: none
		sourceColumn: CORPO HÍDRICO / TRECHO

		annotation SummarizationSetBy = Automatic

	column '* EXTENSÃO (m)'
		dataType: double
		formatString: #,0.00
		lineageTag: 6846138b-ea7e-4ed0-9eea-3af4f54154c8
		summarizeBy: sum
		sourceColumn: * EXTENSÃO (m)

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column INÍCIO
		dataType: dateTime
		formatString: dd/mm/yy
		lineageTag: a16c8ae0-fdbc-4f97-b39d-4f0155a68b7b
		summarizeBy: none
		sourceColumn: INÍCIO

		variation Variation
			isDefault
			relationship: e76ad678-19ca-45e4-a97e-dfb759eb2a5d
			defaultHierarchy: LocalDateTable_c5951ed3-c769-4b98-9c11-3a5accd66c09.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column TÉRMINO
		dataType: dateTime
		formatString: dd/mm/yy
		lineageTag: 19cc9bb1-7cd9-4107-9f8b-093a963240b5
		summarizeBy: none
		sourceColumn: TÉRMINO

		variation Variation
			isDefault
			relationship: 086f5030-fd41-4d98-bef0-c6d53643ca1a
			defaultHierarchy: LocalDateTable_d4d8ab81-f59b-45ec-b7e9-f9f90690b7cf.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'STATUS DO TRECHO'
		dataType: string
		lineageTag: 7707174a-67f3-4426-a1f5-46b915d2d1a3
		summarizeBy: none
		sourceColumn: STATUS DO TRECHO

		annotation SummarizationSetBy = Automatic

	column 'MANUTENÇÃO DO PLANTIO (TÉRMINO)'
		dataType: dateTime
		formatString: dd/mm/yy
		lineageTag: 3435c31d-a84a-4ba1-b817-eef3fc2d2515
		summarizeBy: none
		sourceColumn: MANUTENÇÃO DO PLANTIO (TÉRMINO)

		variation Variation
			isDefault
			relationship: 31e949b7-ac51-4b45-ad44-4c8b2c3a485f
			defaultHierarchy: LocalDateTable_acfb9948-9466-4dcd-b789-3b8d4c605e60.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column LAT_I
		dataType: double
		lineageTag: 40fac54f-73fa-4f41-b604-1f3b2e2d1323
		dataCategory: Latitude
		summarizeBy: none
		sourceColumn: LAT_I

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LON_I
		dataType: double
		lineageTag: 75ce486f-8b8e-4517-9510-df9bdaab8806
		dataCategory: Longitude
		summarizeBy: none
		sourceColumn: LON_I

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LAT_F
		dataType: double
		lineageTag: 2f19082a-ae05-4167-a252-5d153cf6875a
		dataCategory: Latitude
		summarizeBy: none
		sourceColumn: LAT_F

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LON_F
		dataType: double
		lineageTag: 2b41c14f-5059-48dd-9782-5c6d0139923a
		dataCategory: Longitude
		summarizeBy: none
		sourceColumn: LON_F

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DIRETORIA = Concatenate("D",'C3 - STATUS'[BACIA])
		lineageTag: 90a7437e-635c-4d11-9e95-5f5847bf5610
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'ATESTADO DE CONCLUSÃO'
		dataType: string
		lineageTag: d096b7c1-796b-4fef-84fd-cd4028bfef07
		summarizeBy: none
		sourceColumn: ATESTADO DE CONCLUSÃO

		annotation SummarizationSetBy = Automatic

	column 'TRECHO ABREVIADO' = SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(substitute('C3 - STATUS'[CORPO HÍDRICO / TRECHO],"CÓRREGO","CÓR."),"AFLUENTE","AFL."),"REPRESA","REP."),"RIBEIRÃO","RIB."),"TRECHO","T.")
		lineageTag: d797794a-6c0f-41ac-9005-c15bdac92c9a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'CONTRATO FILTRO' = CONCATENATE("CONTRATO ", 'C3 - STATUS'[CONTRATO])
		lineageTag: 5302689d-aadf-4a99-9737-8561bb9d1a5e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'VALOR MEDIDO'
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 1b19d4ad-6b7f-4380-a782-aec6dfa70056
		summarizeBy: sum
		sourceColumn: VALOR MEDIDO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column GEOCODIGO = SELECTCOLUMNS(FILTER('@ @ MUNICÍPIOS BRASIL','@ @ MUNICÍPIOS BRASIL'[MUNICIPIO]='C3 - STATUS'[MUNICÍPIO]),'@ @ MUNICÍPIOS BRASIL'[GEOCODIGO])
		formatString: 0
		lineageTag: e6b2d779-1fae-4c14-9213-36e6a2851688
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column ID_CONTRATO = CONCATENATE('C3 - STATUS'[Referência],'C3 - STATUS'[CONTRATO])
		lineageTag: c3b75a1a-4529-469b-80d1-f32e31088388
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column GERÊNCIA
		dataType: string
		lineageTag: f8e25998-aaf5-469c-bac7-b01c0adcb3ce
		summarizeBy: none
		sourceColumn: GERÊNCIA

		annotation SummarizationSetBy = Automatic

	column DIVISÃO
		dataType: string
		lineageTag: 1cded37d-4c63-4d1d-bbed-cd051ebf6f2a
		summarizeBy: none
		sourceColumn: DIVISÃO

		annotation SummarizationSetBy = Automatic

	column ID_OS = CONCATENATE(CONCATENATE('C3 - STATUS'[ID_CONTRATO],'C3 - STATUS'[Nº OS]),'C3 - STATUS'[GEOCODIGO])
		lineageTag: 1727f2da-7dd5-4a4e-907e-2aaf285db969
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column ID_TRECHO = CONCATENATE('C3 - STATUS'[ID_OS],SUBSTITUTE('C3 - STATUS'[CORPO HÍDRICO / TRECHO]," ",""))
		lineageTag: 88cb479c-f077-4a94-ba8d-73e73e631cd1
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column REFERÊNCIA
		dataType: string
		lineageTag: 186db7ca-4a00-474d-97c6-6a1f7c06666c
		summarizeBy: none
		sourceColumn: REFERÊNCIA

		annotation SummarizationSetBy = Automatic

	column 'TÉRMINO DO CONTRATO'
		dataType: string
		lineageTag: c09bf591-0baa-4a87-b256-35e171df53f9
		summarizeBy: none
		sourceColumn: TÉRMINO DO CONTRATO

		annotation SummarizationSetBy = Automatic

	column 'Nº OS'
		dataType: string
		lineageTag: 46b1351e-c9ef-4d8e-8ca8-ee928c8fa2a5
		summarizeBy: none
		sourceColumn: Nº OS

		annotation SummarizationSetBy = Automatic

	column 'VOLUME MEDIÇÃO (m³)'
		dataType: double
		lineageTag: fe1f5568-27f9-4425-a3f5-e5579abe56d7
		summarizeBy: sum
		sourceColumn: VOLUME MEDIÇÃO (m³)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'C3 - STATUS' = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(Web.Contents("https://revitalizarrv.sharepoint.com/SupervisaoObras/DESASSOREAMENTO/3%C2%BA%20Ciclo/2%20-%20Arquivos%20de%20Controle/Consolidado%20Corpo%20Hidrico%20-%20Status%20-%20Ciclo%203.xlsx"), null, true),
				    STATUS_Sheet = Fonte{[Item="STATUS",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(STATUS_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"CICLO", Int64.Type}, {"BACIA", type text}, {"CONTRATO", Int64.Type}, {"N° CONTRATO", type text}, {"N° OS", type text}, {"DATA TERMINO OS", type date}, {"REGIÃO ADMINISTRATIVA", type text}, {"MUNICÍPIO", type text}, {"CURSO D´ÁGUA", type text}, {"CORPO HÍDRICO / TRECHO", type text}, {"* EXTENSÃO (m)", Int64.Type}, {"VOLUME MEDIÇÃO (m³)", type number}, {"TERMO DE ADESÃO", type date}, {"INÍCIO", type date}, {"TÉRMINO", type date}, {"STATUS DO TRECHO", type text}, {"MANUTENÇÃO DO PLANTIO (TÉRMINO)", type date}, {"ATESTADO DE CONCLUSÃO", type text}, {"DATA ASSINATURA ATESTADO", type any}, {"OBSERVAÇÕES ", type any}, {"LATITUDE INICIAL (S)", type text}, {"LONGITUDE INICIAL (O/W)", type text}, {"LATITUDE FINAL (S)", type text}, {"LONGITUDE FINAL (O/W)", type text}, {"LAT_I", type number}, {"LON_I", type number}, {"LAT_F", type number}, {"LON_F", type number}, {"RAG", Int64.Type}, {"DIVISÃO", type text}, {"GERÊNCIA", type text}, {"REFERÊNCIA", type text}}),
				    #"Tipo Alterado com Localidade" = Table.TransformColumnTypes(#"Tipo Alterado", {{"DATA TERMINO OS", type date}}, "pt-BR"),
				    #"Tipo Alterado com Localidade1" = Table.TransformColumnTypes(#"Tipo Alterado com Localidade", {{"TERMO DE ADESÃO", type date}}, "pt-BR"),
				    #"Tipo Alterado com Localidade2" = Table.TransformColumnTypes(#"Tipo Alterado com Localidade1", {{"INÍCIO", type date}}, "pt-BR"),
				    #"Tipo Alterado com Localidade3" = Table.TransformColumnTypes(#"Tipo Alterado com Localidade2", {{"TÉRMINO", type date}}, "pt-BR"),
				    #"Tipo Alterado com Localidade4" = Table.TransformColumnTypes(#"Tipo Alterado com Localidade3", {{"MANUTENÇÃO DO PLANTIO (TÉRMINO)", type date}}, "pt-BR"),
				    #"Tipo Alterado com Localidade5" = Table.TransformColumnTypes(#"Tipo Alterado com Localidade4", {{"DATA ASSINATURA ATESTADO", type date}}, "pt-BR"),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado com Localidade5",{"N° CONTRATO", "DATA TERMINO OS", "TERMO DE ADESÃO", "DATA ASSINATURA ATESTADO", "OBSERVAÇÕES ", "LATITUDE INICIAL (S)", "LONGITUDE INICIAL (O/W)", "LATITUDE FINAL (S)", "LONGITUDE FINAL (O/W)", "RAG", "CICLO"}),
				    #"Colunas Filtradas" = Table.SelectRows(#"Colunas Removidas", each ([DIVISÃO] <> 0)),
				    #"Changed Type with Locale" = Table.TransformColumnTypes(#"Colunas Filtradas", {{"VALOR MEDIDO", Currency.Type}}, "pt-BR"),
				    #"Linhas Filtradas" = Table.SelectRows(#"Changed Type with Locale", each ([#"CORPO HÍDRICO / TRECHO"] <> null)),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Linhas Filtradas",{{"N° OS", "Nº OS"}})
				in
				    #"Colunas Renomeadas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

