table 'C3 - CONTRATO CONTROLE'
	lineageTag: 29fc2f38-6dfa-46b6-921d-5b628d521262

	column BACIA
		dataType: string
		lineageTag: 0dc220a7-342a-4f71-b56f-b94f0f8a29c4
		summarizeBy: none
		sourceColumn: BACIA

		annotation SummarizationSetBy = Automatic

	column 'N° do CONTRATO'
		dataType: int64
		formatString: 0
		lineageTag: 6700a98d-4187-4ab1-a3ee-d8bd3d3224bc
		summarizeBy: none
		sourceColumn: N° do CONTRATO

		annotation SummarizationSetBy = User

	column IC
		dataType: string
		lineageTag: 68c5b6dd-f091-4237-806c-d30bc6a4d07f
		summarizeBy: none
		sourceColumn: IC

		annotation SummarizationSetBy = Automatic

	column CONTRATO
		dataType: string
		lineageTag: 367c572d-8966-4dd2-b621-d8abf61c4d91
		summarizeBy: none
		sourceColumn: CONTRATO

		annotation SummarizationSetBy = Automatic

	column 'DATA CELEBRAÇÃO'
		dataType: dateTime
		formatString: dd/mm/yy
		lineageTag: 2046e9da-8971-40af-ae1f-568e755fa002
		summarizeBy: none
		sourceColumn: DATA CELEBRAÇÃO

		variation Variation
			isDefault
			relationship: 820ecf23-07c2-4a15-9bd8-06e2a52ebac8
			defaultHierarchy: LocalDateTable_c423f6f8-9271-4037-a4a2-023bd0d98801.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column 'PRAZO CONTRATUAL'
		dataType: int64
		formatString: 0
		lineageTag: 6c311e4f-8106-4848-9c0d-7a97d9fd253c
		summarizeBy: none
		sourceColumn: PRAZO CONTRATUAL

		annotation SummarizationSetBy = User

	column 'CONCLUSÃO DO CONTRATO'
		dataType: dateTime
		formatString: dd/mm/yy
		lineageTag: 5a7832c3-6c9b-4e7c-a140-728bd63d1c6b
		summarizeBy: none
		sourceColumn: CONCLUSÃO DO CONTRATO

		variation Variation
			isDefault
			relationship: 13bb6c4f-0a33-47ef-9655-64404de114d8
			defaultHierarchy: LocalDateTable_10926013-ad7a-4e85-a288-a7a2a0c3b67f.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column 'PRAZO ADITIVO TOTAL'
		dataType: int64
		formatString: 0
		lineageTag: 34bca650-6b41-45ff-ab27-4da087982996
		summarizeBy: none
		sourceColumn: PRAZO ADITIVO TOTAL

		annotation SummarizationSetBy = User

	column 'TÉRMINO COM ADITIVO'
		dataType: dateTime
		formatString: dd/mm/yy
		lineageTag: 1ef76e3c-8d3e-4693-87ad-8d2117c1b1f3
		summarizeBy: none
		sourceColumn: TÉRMINO COM ADITIVO

		variation Variation
			isDefault
			relationship: 1e58ee51-5fe5-4c40-bb47-fb52b57a9c1a
			defaultHierarchy: LocalDateTable_98e3f860-9be6-473c-9245-d774354b029f.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column 'STATUS DO CONTRATO'
		dataType: string
		lineageTag: 04d8210a-4f13-46d0-a481-d8883f8619a8
		summarizeBy: none
		sourceColumn: STATUS DO CONTRATO

		annotation SummarizationSetBy = Automatic

	column 'VALOR DO CONTRATO'
		dataType: decimal
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 3ac26b97-b79a-445c-a74b-c9767bc68077
		summarizeBy: sum
		sourceColumn: VALOR DO CONTRATO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column 'VALOR ADITIVO'
		dataType: decimal
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: f604a1de-c77b-4a7b-858b-2da743ee3856
		summarizeBy: sum
		sourceColumn: VALOR ADITIVO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column 'VALOR CONTRATUAL COM ADITIVO'
		dataType: decimal
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 9bd1c8fb-1062-40a4-825a-aa7a9f532487
		summarizeBy: sum
		sourceColumn: VALOR CONTRATUAL COM ADITIVO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column DIRETORIA = CONCATENATE("D", 'C3 - CONTRATO CONTROLE'[BACIA])
		lineageTag: 8b658a09-367a-4b5c-bd27-28a157885ad4
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column ID_CONTRATO = CONCATENATE('C3 - CONTRATO CONTROLE'[REFERÊNCIA],'C3 - CONTRATO CONTROLE'[N° do CONTRATO])
		lineageTag: 919e00c7-09df-4efb-9176-f48e8facd8a9
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column REFERÊNCIA
		dataType: string
		lineageTag: 5254ef8a-6f59-4da8-9d19-54fe88a19541
		summarizeBy: none
		sourceColumn: REFERÊNCIA

		annotation SummarizationSetBy = Automatic

	column 'DATA DA PRIMEIRA OS'
		dataType: dateTime
		formatString: dd/mm/yy
		lineageTag: fbe91703-23f9-4f71-976d-c978fb2d5daf
		summarizeBy: none
		sourceColumn: DATA DA PRIMEIRA OS

		variation Variation
			isDefault
			relationship: e6d1aec9-4119-4f69-98d5-0f77415d47b2
			defaultHierarchy: LocalDateTable_625aa63d-9f36-4809-8cd8-84b2c84304c1.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column 'SEI DO CONTRATO'
		dataType: string
		lineageTag: f0f08854-10c6-425a-a68b-610ebb8d32db
		summarizeBy: none
		sourceColumn: SEI DO CONTRATO

		annotation SummarizationSetBy = Automatic

	column 'DIAS ATÉ TÉRMINO' = IF(DATEDIFF(TODAY(),'C3 - CONTRATO CONTROLE'[TÉRMINO COM ADITIVO],DAY)<0,0,DATEDIFF(TODAY(),'C3 - CONTRATO CONTROLE'[TÉRMINO COM ADITIVO],DAY))
		formatString: 0
		lineageTag: 37bb8daf-835f-4083-9a96-85366d1dd85c
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column '% medida' = CALCULATE(SUM('C3 - MEDIÇÕES'[VALOR]),FILTER('C3 - MEDIÇÕES','C3 - MEDIÇÕES'[REFERÊNCIA]='C3 - CONTRATO CONTROLE'[REFERÊNCIA]),FILTER('C3 - MEDIÇÕES','C3 - MEDIÇÕES'[CONTRATO]='C3 - CONTRATO CONTROLE'[N° do CONTRATO]),FILTER('C3 - MEDIÇÕES','C3 - MEDIÇÕES'[STATUS]="MEDIÇÃO SPÁGUAS"))/'C3 - CONTRATO CONTROLE'[VALOR DO CONTRATO]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: a0dd4f6a-9400-4f08-b7d9-3897510014f6
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'FASE DO CONTRATO'
		dataType: string
		lineageTag: 1b86c5e6-777e-44a1-a557-a61465495c1f
		summarizeBy: none
		sourceColumn: FASE DO CONTRATO

		annotation SummarizationSetBy = Automatic

	column 'N CONTRATO FILTRO' = CONCATENATE("CONTRATO ",'C3 - CONTRATO CONTROLE'[N° do CONTRATO])
		lineageTag: 2a66a0d1-ac4f-44e4-922d-f249a8055919
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column <75 = IF(AND(OR(OR('C3 - CONTRATO CONTROLE'[FASE DO CONTRATO]="FORA DE VIGÊNCIA",'C3 - CONTRATO CONTROLE'[FASE DO CONTRATO]="ENCERRAMENTO PROVISÓRIO"),'C3 - CONTRATO CONTROLE'[FASE DO CONTRATO]="ENCERRAMENTO DEFINITIVO"),'C3 - CONTRATO CONTROLE'[% medida]<0.75),"SIM","NÃO")
		lineageTag: 24e0c244-bbf4-4808-82b9-712605e410bb
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'DATA TERMO DE ENCERRAMENTO PROVISÓRIO'
		dataType: dateTime
		formatString: Long Date
		lineageTag: b4aabeec-0626-4c13-8ddf-a0b5001a2169
		summarizeBy: none
		sourceColumn: DATA TERMO DE ENCERRAMENTO PROVISÓRIO

		variation Variation
			isDefault
			relationship: 8992cd65-0fd5-4f37-bfde-2903e95f508c
			defaultHierarchy: LocalDateTable_d74e94b3-ca72-4fbe-934f-490396a7e8c9.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'DATA TERMO DE ENCERRAMENTO DEFINITIVO'
		dataType: dateTime
		formatString: Long Date
		lineageTag: f9a985a1-4e86-4bcd-97cc-5f03ff8d90e4
		summarizeBy: none
		sourceColumn: DATA TERMO DE ENCERRAMENTO DEFINITIVO

		variation Variation
			isDefault
			relationship: 8931bed3-1daa-46ec-8e49-da3ab2554241
			defaultHierarchy: LocalDateTable_241c701c-dd8a-451b-a221-48987c91c216.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition 'C3 - CONTRATO CONTROLE' = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(Web.Contents("https://revitalizarrv.sharepoint.com/SupervisaoObras/DESASSOREAMENTO/3%C2%BA%20Ciclo/2%20-%20Arquivos%20de%20Controle/CONTROLE%20QUANTITATIVOS.xlsx"), null, true),
				    C.CONTRATO_Sheet = Fonte{[Item="C.CONTRATO",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(C.CONTRATO_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"CICLO", Int64.Type}, {"BACIA", type text}, {"N° do CONTRATO", Int64.Type}, {"IC", type text}, {"PREGÃO ELETRÔNICO", type text}, {"SEI DE LICITAÇÃO", type text}, {"CONTRATO", type text}, {"NOTA INFORMATIVA", type text}, {"SEI DO CONTRATO", type text}, {"DATA CELEBRAÇÃO", type date}, {"PRAZO CONTRATUAL", Int64.Type}, {"CONCLUSÃO DO CONTRATO", type date}, {"PRAZO ADITIVO 1", type any}, {"PRAZO ADITIVO 2", type any}, {"PRAZO ADITIVO 3", type any}, {"ADITIVO TOTAL", Int64.Type}, {"TÉRMINO COM ADITIVO", type date}, {"STATUS DO CONTRATO", type text}, {"VALOR DO CONTRATO", type number}, {"VALOR ADITIVO 1", type any}, {"VALOR ADITIVO 2", type any}, {"VALOR ADITIVO 3", type any}, {"VALOR ADITIVO", Int64.Type}, {"VALOR TOTAL", type number}, {"CONTRATADA", type text}, {"GESTOR DO CONTRATO", type text}, {"FISCAL", type text}, {"DATA TERMO DE ENCERRAMENTO PROVISÓRIO", type date}, {"DATA TERMO DE ENCERRAMENTO DEFINITIVO", type date}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"CICLO", "PREGÃO ELETRÔNICO", "SEI DE LICITAÇÃO", "NOTA INFORMATIVA"}),
				    #"Filtered Rows" = Table.SelectRows(#"Colunas Removidas", each ([REFERÊNCIA] <> null)),
				    #"Tipo Alterado com Localidade" = Table.TransformColumnTypes(#"Filtered Rows", {{"DATA CELEBRAÇÃO", type date}}, "pt-BR"),
				    #"Tipo Alterado com Localidade1" = Table.TransformColumnTypes(#"Tipo Alterado com Localidade", {{"CONCLUSÃO DO CONTRATO", type date}}, "pt-BR"),
				    #"Colunas Removidas1" = Table.RemoveColumns(#"Tipo Alterado com Localidade1",{"PRAZO ADITIVO 1", "PRAZO ADITIVO 2", "PRAZO ADITIVO 3"}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Colunas Removidas1",{{"ADITIVO TOTAL", "PRAZO ADITIVO TOTAL"}}),
				    #"Tipo Alterado com Localidade2" = Table.TransformColumnTypes(#"Colunas Renomeadas", {{"TÉRMINO COM ADITIVO", type date}}, "pt-BR"),
				    #"Colunas Removidas2" = Table.RemoveColumns(#"Tipo Alterado com Localidade2",{ "VALOR ADITIVO 1", "VALOR ADITIVO 2", "VALOR ADITIVO 3","CONTRATADA", "GESTOR DO CONTRATO", "FISCAL"}),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Colunas Removidas2",{{"VALOR TOTAL", "VALOR CONTRATUAL COM ADITIVO"}}),
				    #"Tipo Alterado com Localidade3" = Table.TransformColumnTypes(#"Colunas Renomeadas1", {{"VALOR DO CONTRATO", Currency.Type}}, "pt-BR"),
				    #"Tipo Alterado com Localidade4" = Table.TransformColumnTypes(#"Tipo Alterado com Localidade3", {{"VALOR ADITIVO", Currency.Type}}, "pt-BR"),
				    #"Tipo Alterado com Localidade5" = Table.TransformColumnTypes(#"Tipo Alterado com Localidade4", {{"VALOR CONTRATUAL COM ADITIVO", Currency.Type}}, "pt-BR"),
				    #"Changed Type with Locale" = Table.TransformColumnTypes(#"Tipo Alterado com Localidade5", {{"DATA DA PRIMEIRA OS", type date}}, "pt-BR"),
				    #"Changed Type" = Table.TransformColumnTypes(#"Changed Type with Locale",{{"REFERÊNCIA", type text}, {"FASE DO CONTRATO", type text}}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Changed Type", each ([REFERÊNCIA] <> null))
				in
				    #"Linhas Filtradas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

