table 'C3 - OS'
	lineageTag: bd22552c-b755-4cb0-806f-9e49f7ce79b4

	column BACIA
		dataType: string
		lineageTag: bc547f0d-36c5-476f-817e-372c79502c2a
		summarizeBy: none
		sourceColumn: BACIA

		annotation SummarizationSetBy = Automatic

	column 'N° do CONTRATO'
		dataType: int64
		formatString: 0
		lineageTag: ac37e846-f0a4-4bdb-80e1-ffc8d0d52341
		summarizeBy: sum
		sourceColumn: N° do CONTRATO

		annotation SummarizationSetBy = Automatic

	column MUNICÍPIO
		dataType: string
		lineageTag: 24ab44c9-9d0a-4d12-b238-09bc8b9519ac
		summarizeBy: none
		sourceColumn: MUNICÍPIO

		annotation SummarizationSetBy = Automatic

	column 'CORPO HÍDRICO'
		dataType: string
		lineageTag: a43e043e-7a74-424d-9c02-7863ab4b32e1
		summarizeBy: none
		sourceColumn: CORPO HÍDRICO

		annotation SummarizationSetBy = Automatic

	column ITEM
		dataType: string
		lineageTag: c12c3ed5-329c-4fac-94f6-03af3b884687
		summarizeBy: none
		sourceColumn: ITEM
		sortByColumn: ItemFiltro

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column DESCRIÇÃO
		dataType: string
		lineageTag: 2a24b41c-b33f-4265-9ec8-5916ac798c7e
		summarizeBy: none
		sourceColumn: DESCRIÇÃO

		annotation SummarizationSetBy = Automatic

	column UNIDADE
		dataType: string
		lineageTag: c4a29c46-2951-4f7b-b388-9f33110bcf7f
		summarizeBy: none
		sourceColumn: UNIDADE

		annotation SummarizationSetBy = Automatic

	column QUANTIDADE
		dataType: double
		lineageTag: 2ca0ae09-703a-4bb1-af4b-65bf09ac543f
		summarizeBy: sum
		sourceColumn: QUANTIDADE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column VALOR
		dataType: decimal
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: dc8931d3-be2a-4fc3-bd23-7c99612151be
		summarizeBy: sum
		sourceColumn: VALOR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column 'VALOR CALCULADO'
		dataType: double
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 99b06c07-60e8-4225-a28a-f2ab403a47b9
		summarizeBy: sum
		sourceColumn: VALOR CALCULADO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column STATUS
		dataType: string
		lineageTag: 81c13e21-56d4-427c-9133-cb95d1e33c9c
		summarizeBy: none
		sourceColumn: STATUS

		annotation SummarizationSetBy = Automatic

	column CONFERÊNCIA
		dataType: double
		lineageTag: 7b1fd8ea-1ab1-4474-b176-197742e41a67
		summarizeBy: sum
		sourceColumn: CONFERÊNCIA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column REFERÊNCIA
		dataType: string
		lineageTag: 661b0d22-9fa7-4c4a-8b11-bfa3f6ace24c
		summarizeBy: none
		sourceColumn: REFERÊNCIA

		annotation SummarizationSetBy = Automatic

	column ItemFiltro
		dataType: double
		lineageTag: b4656a65-aa1a-40c7-bc50-6c6cc5708720
		summarizeBy: sum
		sourceColumn: ItemFiltro

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ID_CONTRATO_ITEM = CONCATENATE(CONCATENATE('C3 - OS'[REFERÊNCIA],'C3 - OS'[ITEM]), 'C3 - OS'[N° do CONTRATO])
		lineageTag: ffdddd25-15ae-46d6-bacb-742053623fb6
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column GEOCODIGO = SELECTCOLUMNS(FILTER('@ @ MUNICÍPIOS BRASIL','@ @ MUNICÍPIOS BRASIL'[MUNICIPIO]='C3 - OS'[MUNICÍPIO]),'@ @ MUNICÍPIOS BRASIL'[GEOCODIGO])
		formatString: 0
		lineageTag: 46bee347-094d-4050-a02a-f4ee74ea079b
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column ID_OS = CONCATENATE(CONCATENATE(CONCATENATE('C3 - OS'[REFERÊNCIA], 'C3 - OS'[N° do CONTRATO]),'C3 - OS'[Nº OS]), 'C3 - OS'[GEOCODIGO])
		lineageTag: b60cc61c-fcbe-4312-a3ee-23094846cb5a
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Nº OS'
		dataType: string
		lineageTag: ad58c120-0ec2-47eb-ad2b-3bfd8d867dba
		summarizeBy: none
		sourceColumn: Nº OS

		annotation SummarizationSetBy = Automatic

	partition 'C3 - OS' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://revitalizarrv.sharepoint.com/SupervisaoObras/DESASSOREAMENTO/3%C2%BA%20Ciclo/2%20-%20Arquivos%20de%20Controle/CONTROLE%20QUANTITATIVOS.xlsx"), null, true),
				    OS_Sheet = Source{[Item="OS",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(OS_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"BACIA", type text}, {"N° do CONTRATO", Int64.Type}, {"MUNICÍPIO", type text}, {"CORPO HÍDRICO", type text}, {"ITEM", type text}, {"DESCRIÇÃO", type text}, {"UNIDADE", type text}, {"QUANTIDADE", type number}, {"PREÇO TOTAL", type number}, {"PREÇO CALCULADO", type number}, {"STATUS", type text}, {"CONFERÊNCIA", type number}, {"REFERÊNCIA", type text}}),
				    #"Changed Type with Locale" = Table.TransformColumnTypes(#"Changed Type", {{"PREÇO TOTAL", Currency.Type}}, "pt-BR"),
				    Custom1 = Table.DuplicateColumn(#"Changed Type with Locale","ITEM","ItemFiltro"),
				    Custom2 = Table.SplitColumn(Custom1,"ItemFiltro",Splitter.SplitTextByPositions({0,1,2})),
				    Custom3 = Table.ReplaceValue(Custom2, each [ItemFiltro.3], each if [ItemFiltro.3]<>"10" then Text.Combine({"0",[ItemFiltro.3]}) else [ItemFiltro.3], Replacer.ReplaceValue, {"ItemFiltro.3"}),
				    Custom4 = Table.CombineColumns(Custom3,{"ItemFiltro.1","ItemFiltro.3"},Combiner.CombineTextByDelimiter(",", QuoteStyle.None), "ItemFiltro"),
				    #"Removed Columns" = Table.RemoveColumns(Custom4,{"ItemFiltro.2"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Columns",{{"ItemFiltro", type number}, {"Nº OS", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type1",{{"PREÇO TOTAL", "VALOR"}, {"PREÇO CALCULADO", "VALOR CALCULADO"}}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Renamed Columns", each ([CORPO HÍDRICO] <> null))
				in
				    #"Linhas Filtradas"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

