table ITEM
	lineageTag: a3172e85-521c-43a4-be1d-d7e33e6f5ac3

	column ITEM
		dataType: string
		lineageTag: 54631c0b-d85c-4a56-b8a4-d265d87eaac8
		summarizeBy: none
		sourceColumn: ITEM
		sortByColumn: ItemFiltro

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Descrição
		dataType: string
		lineageTag: 7524d878-3c07-46af-b684-da7c21e99474
		summarizeBy: none
		sourceColumn: Descrição

		annotation SummarizationSetBy = Automatic

	column Unidade
		dataType: string
		lineageTag: 5f795ad4-e4a5-4416-b4ea-ca87675156cb
		summarizeBy: none
		sourceColumn: Unidade

		annotation SummarizationSetBy = Automatic

	column ItemFiltro
		dataType: double
		lineageTag: bb38b752-28cf-4c39-bcc1-a961c1ef8ec2
		summarizeBy: sum
		sourceColumn: ItemFiltro

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'ITEM MACRO' = left('ITEM'[ITEM],1)
		lineageTag: e61b7323-f93a-4240-a1ab-88e710633148
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition ITEM = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(Web.Contents("https://revitalizarrv.sharepoint.com/SupervisaoObras/DESASSOREAMENTO/3%C2%BA%20Ciclo/2%20-%20Arquivos%20de%20Controle/CONTROLE%20QUANTITATIVOS.xlsx"), null, true),
				    ATA_Sheet = Fonte{[Item="ATA",Kind="Sheet"]}[Data],
				    #"Colunas Removidas" = Table.RemoveColumns(ATA_Sheet,{"Column4"}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Colunas Removidas", each ([Column1] <> null)),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Linhas Filtradas", [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"DIRETORIA", type text}, {"Quantidade - Ata", type number}, {"Preço Unitário (com BDI)", type number}, {"Preço Total ATA", type number}, {"Item", type text}, {"Item_", Int64.Type}}),
				    #"Tipo Alterado com Localidade" = Table.TransformColumnTypes(#"Tipo Alterado", {{"Preço Unitário (com BDI)", Currency.Type}}, "pt-BR"),
				    #"Tipo Alterado com Localidade1" = Table.TransformColumnTypes(#"Tipo Alterado com Localidade", {{"Preço Total ATA", Currency.Type}}, "pt-BR"),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado com Localidade1",{{"Item", "ITEM"}, {"Quantidade - Ata", "QUANTIDADE-ATA"}, {"Preço Unitário (com BDI)", "PREÇO UNITÁRIO"}, {"Preço Total ATA", "VALOR-ATA"}, {"DIRETORIA", "BACIA"}}),
				    Custom1 = Table.DuplicateColumn(#"Colunas Renomeadas","ITEM","ItemFiltro"),
				    Custom2 = Table.SplitColumn(Custom1,"ItemFiltro",Splitter.SplitTextByPositions({0,1,2})),
				    Custom3 = Table.ReplaceValue(Custom2, each [ItemFiltro.3], each if [ItemFiltro.3]<>"10" then Text.Combine({"0",[ItemFiltro.3]}) else [ItemFiltro.3], Replacer.ReplaceValue, {"ItemFiltro.3"}),
				    Custom4 = Table.CombineColumns(#"Custom3",{"ItemFiltro.1","ItemFiltro.3"},Combiner.CombineTextByDelimiter(",", QuoteStyle.None), "ItemFiltro"),
				    #"Removed Columns" = Table.RemoveColumns(Custom4,{"ItemFiltro.2"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns",{{"ItemFiltro", type number}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"QUANTIDADE-ATA", "QUANTIDADE"}, {"VALOR-ATA", "VALOR"}}),
				    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each ([REFERÊNCIA] = "DAT")),
				    #"Removed Columns1" = Table.RemoveColumns(#"Filtered Rows",{"BACIA", "REFERÊNCIA", "Item_", "QUANTIDADE", "PREÇO UNITÁRIO", "VALOR"})
				in
				    #"Removed Columns1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

